version: '3'

services:
  app:
    container_name: app
    depends_on:
      - mongo-primary
      - mongo-secondary
      - mongo-arbiter
    image: scaffold:1.0.0
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - MAIL_URL
      - ROOT_URL
      - MONGO_URL
      - STORAGE_PATH
      - TZ
      - PORT
      - REFRESH_STATIC_PROFILES
      - REFRESH_PERMISSIONS
      - EMAIL_SERVICES
    ports:
    - 80:3000
    volumes:
      - $PWD/.uploads:/opt/app-files
    networks:
      - scaffold-net
  mongo-primary:
    container_name: mongo-primary
    image: bitnami/mongodb:6.0.4
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_DATABASE
    volumes:
      - $PWD/data:/bitnami
      - $PWD/database:/opt/database
    networks:
      - scaffold-net
  mongo-secondary:
    container_name: mongo-secondary
    image: bitnami/mongodb:6.0.4
    restart: always
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_INITIAL_PRIMARY_HOST
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY
    networks:
      - scaffold-net
  mongo-arbiter:
    container_name: mongo-arbiter
    image: bitnami/mongodb:6.0.4
    restart: always
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_INITIAL_PRIMARY_HOST
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY
    networks:
      - scaffold-net
networks:
  scaffold-net:
